import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-surface">
      <div className="max-w-2xl mx-auto px-6 py-12">
        <Link
          href="/"
          className="inline-flex items-center gap-2 text-xs text-text-muted hover:text-text-secondary mb-10 transition-colors"
        >
          <ArrowLeft size={12} />
          Back
        </Link>

        <h1 className="text-2xl font-semibold text-text-primary mb-2">Terms of Service</h1>
        <p className="text-xs text-text-muted mb-10">Effective March 2025 · Council of Elites</p>

        <div className="space-y-8 text-sm text-text-secondary leading-relaxed">
          <section>
            <h2 className="text-base font-semibold text-text-primary mb-3">1. What Council of Elites Is</h2>
            <p>
              Council of Elites is an AI advisory product that generates multi-perspective responses to user questions using AI language models. The product is intended for educational, reflective, and brainstorming purposes only.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-text-primary mb-3">2. AI-Generated Content</h2>
            <p className="mb-3">
              All responses in Council of Elites are generated by AI models. AI can make mistakes, misrepresent facts, and generate content that is inaccurate, incomplete, or misleading. You should not rely on AI-generated responses as your sole basis for any important decision.
            </p>
            <p>
              In particular, nothing generated by Council of Elites constitutes legal, financial, medical, psychological, or other professional advice. Always consult qualified professionals for decisions in these areas.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-text-primary mb-3">3. AI-Inspired Perspectives</h2>
            <p className="mb-3">
              Some advisor personas on Council of Elites are described as being &quot;inspired by&quot; real individuals. These perspectives are generated by AI based solely on publicly available materials: published essays, books, interviews, speeches, and other public statements attributed to those individuals.
            </p>
            <p className="mb-3">
              <strong className="text-text-primary">These personas are not affiliated with, endorsed by, or representative of the named individuals or any organizations they are associated with.</strong> They do not reflect private views, unpublished opinions, current thinking, or anything not in the public record.
            </p>
            <p className="mb-3">
              The use of publicly available materials to build informational and educational AI tools is a common practice. However, we acknowledge that AI-generated content may not accurately reflect the nuances of the individuals&apos; actual views, and we make no warranty to that effect.
            </p>
            <p>
              If you are an individual named in our product and have concerns, please contact us and we will address them promptly.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-text-primary mb-3">4. No Professional Advice</h2>
            <p>
              Council of Elites does not provide legal, financial, medical, psychological, tax, investment, or any other form of professional advice. Responses from all advisor personas — including domain-expert-inspired personas — are for educational and reflective purposes only and should not be acted upon without consulting appropriate professionals.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-text-primary mb-3">5. User Conduct</h2>
            <p>You agree not to use Council of Elites to:</p>
            <ul className="list-disc list-inside mt-2 space-y-1 text-text-muted">
              <li>Harass, defame, or harm any individual</li>
              <li>Generate illegal content</li>
              <li>Attempt to manipulate or jailbreak the AI models</li>
              <li>Impersonate individuals or organizations</li>
              <li>Scrape or systematically extract content</li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-semibold text-text-primary mb-3">6. Data and Privacy</h2>
            <p>
              We collect and store your questions, council sessions, and feedback to provide the service and improve it. We use Google OAuth for authentication. We may use anonymized, aggregated usage data for analytics. We will never sell your personal data to third parties.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-text-primary mb-3">7. Limitation of Liability</h2>
            <p>
              Council of Elites is provided &quot;as is.&quot; We make no warranties about the accuracy, completeness, or fitness of AI-generated responses. To the maximum extent permitted by law, we are not liable for any damages arising from your use of this product, including reliance on any AI-generated content.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-text-primary mb-3">8. Changes</h2>
            <p>
              We may update these terms at any time. Continued use of the service after changes constitutes acceptance of the revised terms.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-text-primary mb-3">9. Contact</h2>
            <p>
              If you have any questions or concerns about these terms, the product, or the use of any individual&apos;s publicly stated views, please reach out to us.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
